// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type OauthAccessToken struct {
	ID            int32              `json:"id"`
	OauthClientID pgtype.Int4        `json:"oauth_client_id"`
	UserID        int32              `json:"user_id"`
	Token         pgtype.Text        `json:"token"`
	Scope         pgtype.Text        `json:"scope"`
	ExpiredAt     pgtype.Timestamptz `json:"expired_at"`
	CreatedBy     pgtype.Int4        `json:"created_by"`
	UpdatedBy     pgtype.Int4        `json:"updated_by"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

type Post struct {
	ID        int32       `json:"id"`
	Title     string      `json:"title"`
	Body      pgtype.Text `json:"body"`
	UserID    pgtype.Int4 `json:"user_id"`
	Status    pgtype.Text `json:"status"`
	CreatedAt time.Time   `json:"created_at"`
}

type User struct {
	ID        int32     `json:"id"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	CreatedAt time.Time `json:"created_at"`
}
