// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) error
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id int32) (User, error)
	GetUsers(ctx context.Context) ([]User, error)
	OauthCreate(ctx context.Context, arg OauthCreateParams) (OauthAccessToken, error)
	OauthFindOneByAccessToken(ctx context.Context, token pgtype.Text) (OauthAccessToken, error)
}

var _ Querier = (*Queries)(nil)
