// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package persistence

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetAccountByEmail(ctx context.Context, email string) (Account, error)
	GetAccountById(ctx context.Context, id uuid.UUID) (Account, error)
	GetAccounts(ctx context.Context) ([]Account, error)
	UpsertAccount(ctx context.Context, arg UpsertAccountParams) (uuid.UUID, error)
}

var _ Querier = (*Queries)(nil)
