// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: role.sql

package persistence

import (
	"context"
)

const getRoleByName = `-- name: GetRoleByName :one
select id, name, created_at, updated_at, deleted_at
from role 
where name = $1
`

func (q *Queries) GetRoleByName(ctx context.Context, name Rolename) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByName, name)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
